context:
  version: "0.17.18"

package:
  name: svelte-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/svelte-language-server/-/svelte-language-server-${{ version }}.tgz
  sha256: 6b50165b522055f28a8265be1714c432989e22b283876d1102787694e904a697

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - svelteserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Svelte Language Server
  homepage: https://github.com/sveltejs/language-tools
  repository: https://github.com/sveltejs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
