context:
  version: "0.18.0"

package:
  name: svelte-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/svelte-language-server/-/svelte-language-server-${{ version }}.tgz
  sha256: af631f49437b309bb14531255d48482693f43db71382721cd52b6e8d7e8df69f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - svelteserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Svelte Language Server
  homepage: https://github.com/sveltejs/language-tools
  repository: https://github.com/sveltejs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
