context:
  version: "0.17.30"

package:
  name: svelte-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/svelte-language-server/-/svelte-language-server-${{ version }}.tgz
  sha256: 6e74337faff625c23753db019d8097a7f8ed113c4632536896aaa49f82483c8c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - svelteserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Svelte Language Server
  homepage: https://github.com/sveltejs/language-tools
  repository: https://github.com/sveltejs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
