context:
  version: "0.18.1"

package:
  name: svelte-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/svelte-language-server/-/svelte-language-server-${{ version }}.tgz
  sha256: 6c23eb03fdd836fee1147af5832f83e903b143ac80c57d008853990b94c8cd81

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - svelteserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Svelte Language Server
  homepage: https://github.com/sveltejs/language-tools
  repository: https://github.com/sveltejs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
